version: '3.7'

services:
  web:
    build: .
    command: python /django-to-do/manage.py runserver 0.0.0.0:8000
    
    volumes:
      - .:/django-to-do

    ports:
      - 8000:8000
    
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data: