# Generated by Django 4.1 on 2022-08-26 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='thing',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='thing',
            old_name='completed',
            new_name='status',
        ),
    ]
