# Generated by Django 4.1 on 2022-08-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_rename_thing_thing_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
