# Generated by Django 4.1 on 2022-08-26 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0004_alter_thing_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='status',
            new_name='completed',
        ),
    ]
