# Generated by Django 4.1 on 2022-08-28 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0005_rename_status_thing_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='creation_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
