# Generated by Django 4.1 on 2022-08-28 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0007_alter_thing_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
